public with sharing class Race 
{
    // choose the appropriate variable type here
    racers;

    public Race() 
    {
        // initialise racers
    }

    public void addRacer(update_type_here racer)
    {
        // add the racer to the racers variable
    }

    public void start() 
    {
        // iterate all racers and ask them to start
    }

    public void flatOut()
    {
        // iterate all racers, move them up through their gears until
        // there are no more left
    }

    public void finish()
    {
        // iterate all racers, move them down through their gears
        // until they are in first, then ask them to stop

        // all racers should drop down one gear at a time.
        // once a racer has hit first gear it should be skipped
    }
}
